name: CannoliShop
version: 1.2.2
author: cannoli_cat
main: cannolicat.cannolishop.CannoliShop
api-version: '1.20'
softdepend: [MythicMobs]
commands:
  cshop:
    description: /cshop <admin/show> <player>
    usage: /<command> <args> <args1>
    permission: cannolishop.command