name: CannoliShop
version: '${project.version}'
main: cannolicat.cannolishop.CannoliShop
api-version: '1.20'
commands:
  cshop:
    usage: /<command> <args> <args1>
    permission: cannolishop.command